### ISSUE TITLE
Build Sucessful - CLI / Terminal opens up everytime I start executable (MacOS)

### ISSUE THREAD

**Issue by java4tech** [gluonhq/client-maven-plugin#220]
I have successfully created executable for both Mac and Windows. But on Mac, Every time I open the executable file another CLI/Terminal window open's up and I have to manual close it. Closing Terminal Window also closes the Application. I wasn't sure where this issue belong. So I'm leaving it here. Let me know if I need to move it somewhere else.
Specs:

MacOS Catalina: 10.15.6
Xcode version: 11.6
graalvm-ce-java11-20.2.0-dev and graalvm-ce-java11-20.3.0-dev tried both
Maven plugin: 0.1.30

**Comment by mipastgt** [comment]
According to my experience this only happens when you launch the executable via double-click. If you launch it from the command line of a terminal window, either directly or through `mvn client:run`, there is no such additional window. This seems to be the normal behavior on the Mac because the client-maven-plugin only produces an executable file but not a properly packaged `.app` folder. This final step still seems to be on the ToDo list.
