### ISSUE TITLE
Build Android apk is possible on Windows also - in WSL2 and Ubuntu

### ISSUE THREAD

**Issue by ltorok** [gluonhq/client-maven-plugin#254]
Build Android apk is possible on Windows/WSL2/Ubuntu.
Useful links:
[Install Windows Subsystem for Linux (WSL) on Windows 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10)
1. Install Ubuntu 20.04 LTS from Microsoft Store
2. Install Maven 3.6.3 in Ubuntu (here - made sure to use the maven from Ubuntu :-) )
3. Next follow instructions on [Gluon Client Plugin Documentation](https://docs.gluonhq.com/client/0.1.32/)
3.1. capture 2.1. GraalVM
3.2. capture 2.2. Java
3.3. 2.3. Linux (install gcc and ld - this already was installed on Ubuntu)
3.4. capture 2.7. Android - The Android SDK will be downloaded automatically by the client plugin and configured with the required packages. - I confirm, yes it is.

**Comment by jperedadnr** [comment]
This is mentioned now from https://docs.gluonhq.com/client/#_android, so I'll close this issue.

**Comment by DeanWookey** [comment]
I'm using WSL. I did encounter one problem when setting up: https://github.com/oracle/graal/issues/2917. I'm not sure if there was something unique about my setup, but the workaround I posted there should help anyone with the same issue.

The next big issue is getting the apk on a device and running it. I wasn't able to get an emulator working on the host and getting the WSL adb to connect to it, but I think it should be possible. In the end I'm using a real device.

Steps to do that are:

If you don't have adb then get it: https://developer.android.com/studio/releases/platform-tools. You should also enable usb debugging on your phone.

On the Windows host, connect your device with USB and enable wifi debugging using the command:

```
adb tcpip 5555
```

If it doesn't say "restarting in TCP mode port: 5555", then try "adb kill-server", followed by "adb usb", followed by "adb devices" to make sure your device is listed, and then running "adb tcpip 5555".

Now it should be possible to disconnect your device from your computer and connect adb via the network.

To connect to it in WSL, first get the IP address of your phone on the network, then the steps I used were to get substrate to start adb with "mvn client:install". That fails the first time because it has no devices. Then run:

```
~/.gluon/substrate/Android/platform-tools/adb connect 192.168.0.121:5555
```

where 192.168.0.121 should be replaced with the IP address of your device.

Then you can run "mvn client:install" again and hopefully it all goes smoothly. If things keep giving issues, then running adb kill-server on both sides and redo everything.

**Comment by mipastgt** [comment]
@DeanWookey I do not quite get your point. 

1. Why do you want to install `adb` manually? You later use it yourself from the automatically installed platform-tools in `.gluon/substrate...`
2. Why does the default `mvn client:install` via USB not work for you? Doing it via Wifi is an alternative but why do you need it.

Just asking.

**Comment by DeanWookey** [comment]
> @DeanWookey I do not quite get your point.
> 
> 1. Why do you want to install `adb` manually? You later use it yourself from the automatically installed platform-tools in `.gluon/substrate...` anyway.
> 2. Why does the default `mvn client:install` via USB not work for you? Doing it via Wifi is an alternative but why do you need it.
> 
> Just asking.

2. In Linux, adb couldn't see the device attached via USB. I'm not sure if there is an easy way around that.
1. Because I couldn't get adb to see the device on Linux, I need 2 adb's. One on the host Windows that can see the device which can put it in wifi mode, and the one in Linux do actually install and run the apk. The one I install manually is the one for Windows. This machine I'm on didn't have Android studio installed at the time, so I just installed adb itself on Windows.

**Comment by mipastgt** [comment]
Thanks. That was not clear to me from your original post. So these are basically pure WSL2/Linux incompatibilities.

**Comment by DeanWookey** [comment]
I appreciate you clarifying. I just wanted to post what I did here because it took me a while to get things working.

I'm guessing there might be a way to get it to work with USB directly, or possibly not. I can't remember exactly what I read that lead me down this path. I would be interested if anyone does know how to get USB working, although once this is running, it works great.
